name: build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  web-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - 
        name: Install Node Modules (client)
        run: npm install
        working-directory: ./web/client
      - 
        name: Use Tag as Version
        run: npm version --no-git-tag-version ${GITHUB_REF#refs/tags/}
        working-directory: ./web/client
      - 
        name: Build Client
        run: npm run build
        working-directory: ./web/client
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=auto
          images: ghcr.io/${{ github.repository_owner }}/onboardpi-web
          tags: type=semver,pattern={{version}}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./web
          file: ./web/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/onboardpi-web:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/onboardpi-web:buildcache,mode=max

  obd-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=auto
          images: ghcr.io/${{ github.repository_owner }}/onboardpi-obd
          tags: type=semver,pattern={{version}}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./obd
          file: ./obd/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/onboardpi-obd:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/onboardpi-obd:buildcache,mode=max
